### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by MavenW** [ananjaser1211/Apollo#1]
Is this kernel compatible with the Note 10 Lite (N770F) Android 13 (OneUI 5.1)?

**Comment by duhansysl** [comment]
@MavenW no its not compatible with Note10 Lite SM-N770F, only compatible with S9 / S9+ / Note9 Exynos

**Comment by MavenW** [comment]
> @MavenW no its not compatible with Note10 Lite SM-N770F, only compatible with S9 / S9+ / Note9 Exynos

mmm so could I compile a new version of ApolloKernel compatible with the Note 10 lite? I thought it was compatible because I saw the name of the device in the list of changes.

**Comment by duhansysl** [comment]
@MavenW this kernel source is based on stock Note9 kernel, only added/updated stuff from note10 lite according to our needs. so im pretty sure you cant make it work on note10 lite without efforts / proper driver and stuffs.
